name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: label change test1
      run: | 
        pwd
        ls
    - name: test the github actions's behavior about cpp
      run: |
        cd test_code_for_test_environment
        clang++ main.cpp -o first_CICD_experience.out
        ./first_CICD_experience.out
    - name: test the github actions's behavior about make README
      run: |
        pwd
        cd test_code_for_test_environment
        pwd
        ls
        touch README.md
        echo "# algorithm_box's CI CD test\n this README made by github actions" >README.md
        cd ../
        pwd
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add ./test_code_for_test_environment/README.md
        git commit -m 'update README.md'
        git push origin HEAD:main

