name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install OpenCV
      run: | 
        wget https://github.com/opencv/opencv/archive/3.2.0.zip
        unzip 3.2.0.zip
        cd opencv-3.2.0
        cmake -D CMAKE_BUILD_TYPE=RELEASE ||cat /home/runner/work/algorithm_box/algorithm_box/opencv-3.2.0/CMakeFiles/CMakeOutput.log
        make -j $(($(nproc) + 1))
        sudo make install
        sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
        sudo ldconfig
    - name: label change test1
      run: | 
        pwd
        ls
    - name: test the github actions's behavior about cpp
      run: |
        cd test_code_for_test_environment
        clang++ main.cpp -o first_CICD_experience.out
        ./first_CICD_experience.out
        rm -f ./first_CICD_experience.out
    - name: test the github actions's behavior about make README
      run: |
        pwd
        cd test_code_for_test_environment
        pwd
        ls
        echo "# algorithm_box's CI CD test
        this README made by github actions
        # output from program
        " >README.md
        clang++ main.cpp -o first_CICD_experience.out
        ./first_CICD_experience.out>>README.md
        rm -f ./first_CICD_experience.out
        cd ../
        pwd

        git config --global user.name "${{github.actor}}"
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git add ./test_code_for_test_environment/README.md
        git status
        git commit -m 'update README.md' || exit 0
        git push origin HEAD:main

    - name: build and run the cpp review project
      run: |
        pwd
        cd cpp/review_about_cpp
        pwd
        ls
        cat _readme_about_this_project.md > README.md

        cmake -S . -B build
        cmake --build build
        ./build/*.out >> README.md
        git config --global user.name "${{github.actor}}"
        git config --global user.email "${{github.actor}}@users.noreply.github.com"
        git add ./README.md
        git status
        git commit -m 'update README.md' || exit 0
        git push origin HEAD:main
        